runtime: python39


entrypoint: gunicorn -t 0 -b :$PORT main:app

instance_class: F1

automatic_scaling:
  max_instances: 1
  target_cpu_utilization: 0.95
  max_concurrent_requests: 120

  min_idle_instances: 0
  max_idle_instances: 0
  min_pending_latency: 15s
  max_pending_latency: 15s
  
env_variables:
    PYTHONUNBUFFERED: "true"

